__author__ = 'SinLapis'

welcome = '220 Welcome! Please put in your username and password.'
quit = '221 Close connection.'
need_password = '331 Require password.'
command_error = '500 Can not recognize the command.'
login_success = '230 You have logged in successfully.'
login_error = '530 Username or password is incorrect. Please retry.'
implement_error = '502 Can not implement the command.'
command_implement = '200 Complete the command.'
unavailable_file = '550 Wrong filename or unavailable file.'
need_account = '332 Need account for login'
transfer_complete = '226 Transfer complete.'
transfer_ready = '150 Open data port'
deny_service = '400 Service is not available.'